# Generated by Django 3.2.9 on 2021-11-16 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='apiusers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=5)),
                ('id_type', models.CharField(max_length=3)),
                ('slot_begining', models.IntegerField()),
                ('slot_end', models.IntegerField()),
            ],
        ),
    ]
