# Generated by Django 3.2.9 on 2021-11-16 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='interviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=5)),
                ('id_type', models.CharField(max_length=3)),
                ('slot_begining', models.IntegerField()),
                ('slot_end', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='apiusers',
            new_name='interviewee',
        ),
    ]
