# Generated by Django 3.2.9 on 2021-11-16 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211117_0120'),
    ]

    operations = [
        migrations.CreateModel(
            name='applicant',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('id_type', models.CharField(max_length=3)),
                ('slot_begining', models.IntegerField()),
                ('slot_end', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='interviewee',
        ),
        migrations.RemoveField(
            model_name='interviewer',
            name='uid',
        ),
        migrations.AlterField(
            model_name='interviewer',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='interviewer',
            name='id_type',
            field=models.CharField(max_length=5),
        ),
    ]
