# Generated by Django 3.2.9 on 2021-11-16 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211117_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='id_type',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='interviewer',
            name='id_type',
            field=models.CharField(max_length=10),
        ),
    ]
