# Generated by Django 3.2.9 on 2021-11-17 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211117_0451'),
    ]

    operations = [
        migrations.CreateModel(
            name='applicant_dw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('slot_begining', models.IntegerField()),
                ('slot_end', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='interviewer_dw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('slot_begining', models.IntegerField()),
                ('slot_end', models.IntegerField()),
            ],
        ),
    ]
